### ISSUE TITLE
[BUG] Local variable overwrites horizon to a different value

### ISSUE THREAD

**Issue by JackCole1777** [health-data-science-OR/forecasting#24]
In -> 01 basics -> 01 practical notebooks -> Practical 2 Solutions -> Exercise 1.4 there is a local variable that remains from 1.3, where horizon is set to 1. This variable is then re-used in the model fitting for loop in the 1.4 Solution, yet the horizon passed to the rolling_forecast_origin function is 2. We should re-set this variable to 2, or we could just pass in 1 to the rolling_forecast_origin to ensure the correct values are obtained.

**Comment by TomMonks** [comment]
Fixed for 2025 cohort with thanks!
