### ISSUE TITLE
Sliding Window Range in Exercise 1 autoregression_keras_part1_SOLUTIONS.ipynb

### ISSUE THREAD

**Issue by ploginovic** [health-data-science-OR/forecasting#30]
https://github.com/health-data-science-OR/forecasting/blob/master/06_neural_networks/feedforward/keras/autoregression_keras_part1_SOLUTIONS.ipynb

**Exercise 1** sliding_window( ) (line 967) does not include the last slice. This is because range is defined as  "for i in range(0, len(train) - window_size - horizon)" without +1.

**Comment by TomMonks** [comment]
Thanks @ploginovic . Fixed in upcoming 2025 release and acknowledgement added.
